'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class en_US
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SimWorldLib.en-US", GetType(en_US).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Activity.
    '''</summary>
    Friend Shared ReadOnly Property Activity() As String
        Get
            Return ResourceManager.GetString("Activity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The age of the Creature. .
    '''</summary>
    Friend Shared ReadOnly Property Age() As String
        Get
            Return ResourceManager.GetString("Age", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether the Creature is alive. EnergyExpand shows base level energy expenditure per second of the Creature..
    '''</summary>
    Friend Shared ReadOnly Property Alive() As String
        Get
            Return ResourceManager.GetString("Alive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The opacity of the map layer (255 is not transparent, and 0 is total transparent. ).
    '''</summary>
    Friend Shared ReadOnly Property Alpha() As String
        Get
            Return ResourceManager.GetString("Alpha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The average value..
    '''</summary>
    Friend Shared ReadOnly Property Avg() As String
        Get
            Return ResourceManager.GetString("Avg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Behavior.
    '''</summary>
    Friend Shared ReadOnly Property Behavior() As String
        Get
            Return ResourceManager.GetString("Behavior", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Energy that the Creature&apos;s offsprings have at birth. .
    '''</summary>
    Friend Shared ReadOnly Property BornEnergy() As String
        Get
            Return ResourceManager.GetString("BornEnergy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The mass of the Creature&apos;s offsprings at birth. .
    '''</summary>
    Friend Shared ReadOnly Property BornWeight() As String
        Get
            Return ResourceManager.GetString("BornWeight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Date and time the World file is created. .
    '''</summary>
    Friend Shared ReadOnly Property CreationTime() As String
        Get
            Return ResourceManager.GetString("CreationTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The population of the creatures in simulation in the World. .
    '''</summary>
    Friend Shared ReadOnly Property CreatureCount() As String
        Get
            Return ResourceManager.GetString("CreatureCount", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to List of the Creatures within the World. .
    '''</summary>
    Friend Shared ReadOnly Property Creatures() As String
        Get
            Return ResourceManager.GetString("Creatures", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The length of the daytime in second. .
    '''</summary>
    Friend Shared ReadOnly Property DayLen() As String
        Get
            Return ResourceManager.GetString("DayLen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The length of the whole day in second. .
    '''</summary>
    Friend Shared ReadOnly Property DayTotal() As String
        Get
            Return ResourceManager.GetString("DayTotal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Simulation time resolution/step in second. .
    '''</summary>
    Friend Shared ReadOnly Property DT() As String
        Get
            Return ResourceManager.GetString("DT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether the Creature is eating. .
    '''</summary>
    Friend Shared ReadOnly Property Eating() As String
        Get
            Return ResourceManager.GetString("Eating", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Energy.
    '''</summary>
    Friend Shared ReadOnly Property Energy() As String
        Get
            Return ResourceManager.GetString("Energy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Energy expenditure associated with this state. .
    '''</summary>
    Friend Shared ReadOnly Property EnergyExpense() As String
        Get
            Return ResourceManager.GetString("EnergyExpense", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Environment.
    '''</summary>
    Friend Shared ReadOnly Property Environment() As String
        Get
            Return ResourceManager.GetString("Environment", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ？？？？？？？？？？？？.
    '''</summary>
    Friend Shared ReadOnly Property EtoWRate() As String
        Get
            Return ResourceManager.GetString("EtoWRate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Genetics.
    '''</summary>
    Friend Shared ReadOnly Property Genetics() As String
        Get
            Return ResourceManager.GetString("Genetics", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Genome of the Creature: collection of the math models that determine the phenotypes and behaviors.  .
    '''</summary>
    Friend Shared ReadOnly Property Genome() As String
        Get
            Return ResourceManager.GetString("Genome", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Graphics.
    '''</summary>
    Friend Shared ReadOnly Property Graphics() As String
        Get
            Return ResourceManager.GetString("Graphics", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Number of grid units in the World. .
    '''</summary>
    Friend Shared ReadOnly Property GridCount() As String
        Get
            Return ResourceManager.GetString("GridCount", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Size of the square grids used to locate the Creatures. In order to speed up the simulation running time, we recommend to set the value such that GridCount is less than 300..
    '''</summary>
    Friend Shared ReadOnly Property GridSize() As String
        Get
            Return ResourceManager.GetString("GridSize", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unique GUID of the Creature. .
    '''</summary>
    Friend Shared ReadOnly Property ID() As String
        Get
            Return ResourceManager.GetString("ID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Identity.
    '''</summary>
    Friend Shared ReadOnly Property Identity() As String
        Get
            Return ResourceManager.GetString("Identity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Energy the Creature possesses. .
    '''</summary>
    Friend Shared ReadOnly Property Joule() As String
        Get
            Return ResourceManager.GetString("Joule", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Rate of the distribution. .
    '''</summary>
    Friend Shared ReadOnly Property Lambda() As String
        Get
            Return ResourceManager.GetString("Lambda", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Life.
    '''</summary>
    Friend Shared ReadOnly Property Life() As String
        Get
            Return ResourceManager.GetString("Life", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Maximum age of the Creature. .
    '''</summary>
    Friend Shared ReadOnly Property Lifespan() As String
        Get
            Return ResourceManager.GetString("Lifespan", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The number of offsprings the Creature has for each mating. .
    '''</summary>
    Friend Shared ReadOnly Property LitterSize() As String
        Get
            Return ResourceManager.GetString("LitterSize", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether the Creature is shown highlighted. .
    '''</summary>
    Friend Shared ReadOnly Property Marked() As String
        Get
            Return ResourceManager.GetString("Marked", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Color of the Marker. .
    '''</summary>
    Friend Shared ReadOnly Property MarkerColor() As String
        Get
            Return ResourceManager.GetString("MarkerColor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Size of the Creature shown in the Stage. .
    '''</summary>
    Friend Shared ReadOnly Property MarkerSize() As String
        Get
            Return ResourceManager.GetString("MarkerSize", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether the Creature is ready to mate and give birth. .
    '''</summary>
    Friend Shared ReadOnly Property MateReady() As String
        Get
            Return ResourceManager.GetString("MateReady", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Maximum energy stored by the Creature, i.e. its energy capacity. .
    '''</summary>
    Friend Shared ReadOnly Property MaxEnergyStorage() As String
        Get
            Return ResourceManager.GetString("MaxEnergyStorage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Upper bound of the model. .
    '''</summary>
    Friend Shared ReadOnly Property Maximum() As String
        Get
            Return ResourceManager.GetString("Maximum", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lower bound of the model. .
    '''</summary>
    Friend Shared ReadOnly Property Minimum() As String
        Get
            Return ResourceManager.GetString("Minimum", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The minimum age for the Creature to be able to mate. .
    '''</summary>
    Friend Shared ReadOnly Property MinMateAge() As String
        Get
            Return ResourceManager.GetString("MinMateAge", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether the Creature is moving. .
    '''</summary>
    Friend Shared ReadOnly Property Move() As String
        Get
            Return ResourceManager.GetString("Move", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The 3D velocity vector of the Creature at the given instance. .
    '''</summary>
    Friend Shared ReadOnly Property MovingVector() As String
        Get
            Return ResourceManager.GetString("MovingVector", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mean of the distribution. .
    '''</summary>
    Friend Shared ReadOnly Property Mu() As String
        Get
            Return ResourceManager.GetString("Mu", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The length of the night in second. .
    '''</summary>
    Friend Shared ReadOnly Property NightLen() As String
        Get
            Return ResourceManager.GetString("NightLen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Probability of yielding one. .
    '''</summary>
    Friend Shared ReadOnly Property p() As String
        Get
            Return ResourceManager.GetString("p", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether the phenotype of the Gene is perceptible to other Creatures. .
    '''</summary>
    Friend Shared ReadOnly Property Perceptible() As String
        Get
            Return ResourceManager.GetString("Perceptible", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether the Creature is photosynthesizing. EnergyExpand shows the rate of photosynthesis in energy per second per brightness received. .
    '''</summary>
    Friend Shared ReadOnly Property Photosynthesize() As String
        Get
            Return ResourceManager.GetString("Photosynthesize", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The 3D position of the Creature. .
    '''</summary>
    Friend Shared ReadOnly Property Position() As String
        Get
            Return ResourceManager.GetString("Position", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether the Creature is pregnant. .
    '''</summary>
    Friend Shared ReadOnly Property Pregnant() As String
        Get
            Return ResourceManager.GetString("Pregnant", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The refresh rate of the Dashboard information and the Stage image in multiples of DT. In order to speed up the simulation running time, we recommend to set the value greater than 10. .
    '''</summary>
    Friend Shared ReadOnly Property RefreshRate() As String
        Get
            Return ResourceManager.GetString("RefreshRate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Reproduction.
    '''</summary>
    Friend Shared ReadOnly Property Reproduction() As String
        Get
            Return ResourceManager.GetString("Reproduction", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The path of the Creature file. .
    '''</summary>
    Friend Shared ReadOnly Property SettingPath() As String
        Get
            Return ResourceManager.GetString("SettingPath", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sex of the Creature [Male is True]. For asexual organisms, this property is ignored.  .
    '''</summary>
    Friend Shared ReadOnly Property Sex() As String
        Get
            Return ResourceManager.GetString("Sex", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Standard deviation of the distribution..
    '''</summary>
    Friend Shared ReadOnly Property Sigma() As String
        Get
            Return ResourceManager.GetString("Sigma", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Simulation.
    '''</summary>
    Friend Shared ReadOnly Property Simulation() As String
        Get
            Return ResourceManager.GetString("Simulation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The version of the SimWorld that created the World file. .
    '''</summary>
    Friend Shared ReadOnly Property SimWorldVer() As String
        Get
            Return ResourceManager.GetString("SimWorldVer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The size of the World (width x height x depth). [Positive double x Positive double x Non-negative double]. If the depth is zero, the simulation is 2-dimensional. .
    '''</summary>
    Friend Shared ReadOnly Property Size() As String
        Get
            Return ResourceManager.GetString("Size", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether the Creature is asleep. .
    '''</summary>
    Friend Shared ReadOnly Property Sleep() As String
        Get
            Return ResourceManager.GetString("Sleep", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The species number of the Creature. .
    '''</summary>
    Friend Shared ReadOnly Property Species() As String
        Get
            Return ResourceManager.GetString("Species", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether the Creature is in this state. .
    '''</summary>
    Friend Shared ReadOnly Property State() As String
        Get
            Return ResourceManager.GetString("State", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The sum of the values. .
    '''</summary>
    Friend Shared ReadOnly Property Sum() As String
        Get
            Return ResourceManager.GetString("Sum", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ratio of the light power received from the Sun compare to the maximum value. .
    '''</summary>
    Friend Shared ReadOnly Property SunPowerRatio() As String
        Get
            Return ResourceManager.GetString("SunPowerRatio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The accumulated time since simulation started in second..
    '''</summary>
    Friend Shared ReadOnly Property T() As String
        Get
            Return ResourceManager.GetString("T", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Environment temperature of the World in Celsius. .
    '''</summary>
    Friend Shared ReadOnly Property Temperature() As String
        Get
            Return ResourceManager.GetString("Temperature", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The hue of the map layer. .
    '''</summary>
    Friend Shared ReadOnly Property ThemeColor() As String
        Get
            Return ResourceManager.GetString("ThemeColor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current time of the day. .
    '''</summary>
    Friend Shared ReadOnly Property TimeofDay() As String
        Get
            Return ResourceManager.GetString("TimeofDay", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The length of each transition between day and night in second. .
    '''</summary>
    Friend Shared ReadOnly Property Twilight() As String
        Get
            Return ResourceManager.GetString("Twilight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Utility.
    '''</summary>
    Friend Shared ReadOnly Property Utility() As String
        Get
            Return ResourceManager.GetString("Utility", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whether it is shown. .
    '''</summary>
    Friend Shared ReadOnly Property Visible() As String
        Get
            Return ResourceManager.GetString("Visible", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The maximum distance from the Position to the surroudings the Creature is able to see. .
    '''</summary>
    Friend Shared ReadOnly Property VisionDepth() As String
        Get
            Return ResourceManager.GetString("VisionDepth", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The mass of the Creature. .
    '''</summary>
    Friend Shared ReadOnly Property Weight() As String
        Get
            Return ResourceManager.GetString("Weight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The file name of the World file currently loaded..
    '''</summary>
    Friend Shared ReadOnly Property WorldFile() As String
        Get
            Return ResourceManager.GetString("WorldFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Folder directory that contains the World file and all its creature files..
    '''</summary>
    Friend Shared ReadOnly Property WorldFileDir() As String
        Get
            Return ResourceManager.GetString("WorldFileDir", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Logs associated with the World. .
    '''</summary>
    Friend Shared ReadOnly Property WorldLog() As String
        Get
            Return ResourceManager.GetString("WorldLog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to World File version. .
    '''</summary>
    Friend Shared ReadOnly Property WorldVersion() As String
        Get
            Return ResourceManager.GetString("WorldVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ？？？？？？？？？？？？.
    '''</summary>
    Friend Shared ReadOnly Property WtoERate() As String
        Get
            Return ResourceManager.GetString("WtoERate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The first dimension (Width). .
    '''</summary>
    Friend Shared ReadOnly Property X() As String
        Get
            Return ResourceManager.GetString("X", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The second dimension (Height). .
    '''</summary>
    Friend Shared ReadOnly Property Y() As String
        Get
            Return ResourceManager.GetString("Y", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The third dimension (Depth). .
    '''</summary>
    Friend Shared ReadOnly Property Z() As String
        Get
            Return ResourceManager.GetString("Z", resourceCulture)
        End Get
    End Property
End Class
